const CROSSWORD_WORDS = [
    { word: "ASTRONAUTA", clue: "Profissional que viaja pelo espaço sideral" },
    { word: "BIBLIOTECA", clue: "Local que abriga uma grande coleção de livros" },
    { word: "CACHOEIRA", clue: "Queda d'água em um rio ou curso d'água" },
    { word: "DINOSSAURO", clue: "Animal pré-histórico que dominou a Terra" },
    { word: "ELETRICISTA", clue: "Profissional que trabalha com instalações elétricas" },
    { word: "FORMIGUEIRO", clue: "Habitação subterrânea de colônias de formigas" },
    { word: "GIRAFA", clue: "Animal de pescoço longo nativo da África" },
    { word: "HELICOPTERO", clue: "Aeronave de asas rotativas" },
    { word: "INSTRUMENTO", clue: "Objeto utilizado para realizar uma tarefa ou tocar música" },
    { word: "JARDINEIRO", clue: "Pessoa que cuida de plantas e jardins" },
    { word: "LABIRINTO", clue: "Lugar cheio de caminhos que se cruzam e confundem" },
    { word: "MONTANHA", clue: "Grande elevação natural do terreno" },
    { word: "NASCIMENTO", clue: "Ato de vir ao mundo ou começar a existir" },
    { word: "ORQUESTRA", clue: "Conjunto de músicos que tocam diversos instrumentos" },
    { word: "PASSAGEIRO", clue: "Pessoa que viaja em um veículo sem conduzi-lo" },
    { word: "QUILOMETRO", clue: "Unidade de medida de distância equivalente a mil metros" },
    { word: "REFRIGERADOR", clue: "Aparelho usado para conservar alimentos gelados" },
    { word: "SABONETE", clue: "Produto usado para higiene do corpo" },
    { word: "TELEVISÃO", clue: "Aparelho que transmite imagens e sons à distância" },
    { word: "UNIVERSIDADE", clue: "Instituição de ensino superior e pesquisa" },
    { word: "VELOCIDADE", clue: "Rapidez com que algo se move" },
    { word: "XILOFONE", clue: "Instrumento musical de percussão com barras de madeira" },
    { word: "ZEBRA", clue: "Animal listrado de preto e branco" },
    { word: "ABACAXI", clue: "Fruto tropical com casca áspera e coroa" },
    { word: "BORBOLETA", clue: "Inseto com asas coloridas que passa por metamorfose" },
    { word: "CHOCOLATE", clue: "Alimento feito a partir do cacau" },
    { word: "DIAMANTE", clue: "Pedra preciosa de carbono puro e extrema dureza" },
    { word: "ESCORPIÃO", clue: "Aracnídeo com cauda terminada em um ferrão venenoso" },
    { word: "FOGUETE", clue: "Veículo usado para lançar satélites ou naves espaciais" },
    { word: "GELADEIRA", clue: "Outro nome para o refrigerador doméstico" },
    { word: "HIPOPOTAMO", clue: "Grande mamífero africano que vive perto da água" },
    { word: "INTERNET", clue: "Rede mundial de computadores" },
    { word: "JANELA", clue: "Abertura na parede para entrada de luz e ar" },
    { word: "KIWI", clue: "Fruto pequeno com casca peluda e polpa verde" },
    { word: "LEOPARDO", clue: "Felino ágil e veloz com pelagem manchada" },
    { word: "MORANGO", clue: "Fruto pequeno, vermelho e com sementes externas" },
    { word: "NEBULOSA", clue: "Nuvem interestelar de poeira e gases" },
    { word: "OCEANO", clue: "Vasta extensão de água salgada que cobre a Terra" },
    { word: "PANTANAL", clue: "Maior planície inundável do mundo, situada no Brasil" },
    { word: "QUADRADO", clue: "Figura geométrica com quatro lados iguais" },
    { word: "RELAMPAGO", clue: "Descarga elétrica intensa que ocorre na atmosfera" },
    { word: "SAXOFONE", clue: "Instrumento de sopro feito de metal" },
    { word: "TARTARUGA", clue: "Répteis conhecidos pelo seu casco protetor" },
    { word: "URSO", clue: "Grande mamífero carnívoro ou onívoro" },
    { word: "VAMPIRO", clue: "Ser mitológico que se alimenta de sangue" },
    { word: "WATT", clue: "Unidade de medida de potência elétrica" },
    { word: "XERIFE", clue: "Autoridade policial em certos condados ou cidades" },
    { word: "IOGA", clue: "Prática que combina exercícios físicos e meditação" },
    { word: "ZOOLÓGICO", clue: "Local onde animais são mantidos para exibição" },
    { word: "ALFABETO", clue: "Conjunto de letras usadas na escrita" },
    { word: "BALEIA", clue: "Maior mamífero marinho do mundo" },
    { word: "CARAMELO", clue: "Açúcar derretido e dourado" },
    { word: "DESERTO", clue: "Região árida com pouca chuva e vegetação" },
    { word: "ESMERALDA", clue: "Pedra preciosa de cor verde intensa" },
    { word: "FLORESTA", clue: "Grande área coberta por árvores" },
    { word: "GUITARRA", clue: "Instrumento musical de cordas dedilhadas" },
    { word: "AMBULANCIA", clue: "Veículo para transporte de doentes ou feridos" },
    { word: "INVERNO", clue: "Estação mais fria do ano" },
    { word: "JACARÉ", clue: "Réptil semelhante ao crocodilo" },
    { word: "KOALA", clue: "Marsupial australiano que come eucalipto" },
    { word: "LUA", clue: "Satélite natural da Terra" },
    { word: "MARTELO", clue: "Ferramenta usada para pregar ou quebrar" },
    { word: "NAVIO", clue: "Embarcação de grande porte" },
    { word: "ONÇA", clue: "Felino de grande porte das Américas" },
    { word: "PALAVRA", clue: "Unidade da linguagem com significado" },
    { word: "QUEIJO", clue: "Alimento feito a partir do leite coalhado" },
    { word: "RIO", clue: "Curso natural de água" },
    { word: "SOL", clue: "Estrela central do nosso sistema" },
    { word: "TREM", clue: "Veículo que corre sobre trilhos" },
    { word: "URV", clue: "Unidade Real de Valor (histórico do Brasil)" },
    { word: "VENTO", clue: "Ar em movimento natural" },
    { word: "XALE", clue: "Peça de vestuário usada sobre os ombros" },
    { word: "YOGA", clue: "Grafia alternativa para a prática milenar" },
    { word: "ZINCO", clue: "Elemento químico metálico" },
    { word: "AMIZADE", clue: "Sentimento de afeição entre pessoas" },
    { word: "BANCO", clue: "Instituição financeira ou móvel para sentar" },
    { word: "CIDADE", clue: "Grande aglomerado urbano" },
    { word: "DINHEIRO", clue: "Meio de troca para bens e serviços" },
    { word: "ESCOLA", clue: "Local destinado ao ensino e aprendizagem" },
    { word: "FERIAS", clue: "Período de descanso do trabalho ou estudos" },
    { word: "GARFO", clue: "Utensílio de mesa com dentes" },
    { word: "HORA", clue: "Unidade de tempo de sessenta minutos" },
    { word: "IGREJA", clue: "Templo religioso cristão" },
    { word: "JOGO", clue: "Atividade de entretenimento com regras" },
    { word: "LIVRO", clue: "Conjunto de folhas de papel impressas" },
    { word: "MESA", clue: "Móvel plano usado para comer ou trabalhar" },
    { word: "NOITE", clue: "Período entre o pôr e o nascer do sol" },
    { word: "OLHO", clue: "Órgão da visão" },
    { word: "PÃO", clue: "Alimento básico feito de farinha e água" },
    { word: "QUARTO", clue: "Cômodo da casa usado para dormir" },
    { word: "ROUPA", clue: "Peças de vestuário humano" },
    { word: "SALA", clue: "Cômodo social de uma casa" },
    { word: "TERRA", clue: "Terceiro planeta do sistema solar" },
    { word: "UVA", clue: "Fruto da videira" },
    { word: "VIDA", clue: "Estado dos seres que nascem e crescem" },
    { word: "WEB", clue: "Rede mundial de computadores" },
    { word: "XÍCARA", clue: "Recipiente pequeno com asa para bebidas" },
    { word: "ZELO", clue: "Grande cuidado ou dedicação" },
    { word: "ARROZ", clue: "Cereal que é base da alimentação brasileira" },
    { word: "BOTA", clue: "Calçado que cobre parte da perna" },
    { word: "COCO", clue: "Fruto do coqueiro" },
    { word: "DADO", clue: "Cubo com números usado em jogos" },
    { word: "EIXO", clue: "Linha imaginária ou real em torno da qual algo gira" },
    { word: "FACA", clue: "Ferramenta de corte usada na cozinha" },
    { word: "GELO", clue: "Água em estado sólido" },
    { word: "HARPA", clue: "Instrumento musical de cordas vertical" },
    { word: "ÍDOLO", clue: "Pessoa ou objeto muito admirado" },
    { word: "JATO", clue: "Fluxo rápido de líquido ou gás" },
    { word: "LAGO", clue: "Grande massa de água cercada por terra" },
    { word: "MODA", clue: "Tendência de vestuário e comportamento" },
    { word: "NIVEL", clue: "Igualdade de altura ou posição" },
    { word: "OURO", clue: "Metal precioso de cor amarela" },
    { word: "PEIXE", clue: "Vertebrado aquático que respira por guelras" },
    { word: "REDE", clue: "Entrelaçamento de fios usado para pescar ou dormir" },
    { word: "SAPO", clue: "Anfíbio que pula e coaxa" },
    { word: "TALA", clue: "Peça usada para imobilizar um membro" },
    { word: "URSO", clue: "Grande mamífero de pelos grossos" },
    { word: "VELA", clue: "Peça de cera usada para iluminação" },
    { word: "XADREZ", clue: "Jogo de tabuleiro estratégico" },
    { word: "ZINCO", clue: "Elemento químico usado em ligas metálicas" },
    { word: "AMORA", clue: "Fruto pequeno e escuro da amoreira" },
    { word: "BALA", clue: "Doce pequeno ou projétil de arma" },
    { word: "CANOA", clue: "Embarcação pequena e estreita" },
    { word: "DOCE", clue: "Alimento com sabor de açúcar" },
    { word: "EMOÇÃO", clue: "Forte sentimento ou reação psicológica" },
    { word: "FESTA", clue: "Comemoração alegre de um evento" },
    { word: "GATO", clue: "Animal doméstico que mia" },
    { word: "HORTA", clue: "Local onde se cultivam hortaliças" },
    { word: "ILHA", clue: "Porção de terra cercada de água" },
    { word: "JOIA", clue: "Objeto de adorno feito de metal precioso" },
    { word: "LAMA", clue: "Mistura de terra e água" },
    { word: "MAÇÃ", clue: "Fruto redondo e comestível da macieira" },
    { word: "NAVIO", clue: "Veículo aquático de grande porte" },
    { word: "OVOS", clue: "Células reprodutivas de aves e répteis" },
    { word: "PIZZA", clue: "Prato italiano redondo de massa com cobertura" },
    { word: "RATO", clue: "Pequeno mamífero roedor" },
    { word: "SOLO", clue: "Superfície da terra onde as plantas crescem" },
    { word: "TIGRE", clue: "Grande felino asiático listrado" },
    { word: "URNA", clue: "Recipiente usado para coletar votos" },
    { word: "VASO", clue: "Recipiente usado para flores ou decoração" },
    { word: "XEROX", clue: "Cópia fotostática de um documento" },
    { word: "ZEBRA", clue: "Animal africano com listras" },
    { word: "AEROPORTO", clue: "Local de pouso e decolagem de aviões" },
    { word: "BICICLETA", clue: "Veículo de duas rodas movido a pedal" },
    { word: "COMPUTADOR", clue: "Máquina eletrônica que processa dados" },
    { word: "DICIONARIO", clue: "Livro que contém o significado das palavras" },
    { word: "ENGENHEIRO", clue: "Profissional que projeta máquinas ou obras" },
    { word: "FOTOGRAFIA", clue: "Imagem capturada por uma câmera" },
    { word: "GEOGRAFIA", clue: "Ciência que estuda a superfície terrestre" },
    { word: "HIDRANTE", clue: "Dispositivo de combate a incêndios na rua" },
    { word: "ILUMINAÇÃO", clue: "Conjunto de luzes em um ambiente" },
    { word: "JORNALISTA", clue: "Profissional que trabalha com notícias" },
    { word: "KILOGRAMA", clue: "Unidade de medida de massa" },
    { word: "LITERATURA", clue: "Arte de escrever livros e poesias" },
    { word: "MATEMATICA", clue: "Ciência que estuda números e medidas" },
    { word: "NAVIGATION", clue: "Ato de conduzir um navio ou veículo" },
    { word: "OBSERVATORIO", clue: "Lugar para observar astros no céu" },
    { word: "PSICOLOGO", clue: "Profissional que estuda o comportamento humano" },
    { word: "QUIMICA", clue: "Ciência que estuda a matéria e suas reações" },
    { word: "RESTAURANTE", clue: "Local onde se servem refeições pagas" },
    { word: "SOCIOLOGIA", clue: "Ciência que estuda as sociedades humanas" },
    { word: "TECNOLOGIA", clue: "Conjunto de conhecimentos e inovações" },
    { word: "ULTRASSOM", clue: "Exame médico que usa ondas sonoras" },
    { word: "VENTILAÇÃO", clue: "Renovação do ar em um ambiente" },
    { word: "XILOGRAFIA", clue: "Técnica de gravura em madeira" },
    { word: "ZEBRADO", clue: "Padrão de listras semelhante à zebra" }
];

if (typeof window !== 'undefined') {
    window.CROSSWORD_WORDS = CROSSWORD_WORDS;
}
